import React from 'react';
import { Button } from '../atoms/Button';

interface WorkflowModalProps {
  isOpen: boolean;
  onClose: () => void;
  projectTitle: string;
  mermaidChartString: string;
}

export default function WorkflowModal({ isOpen, onClose, projectTitle, mermaidChartString }: WorkflowModalProps) {
  if (!isOpen) return null;

  // ONLY Styling the inside boxes generated by Mermaid
  let styledChart = mermaidChartString;
  const boxStyles = `
    classDef default fill:#f8fafc,stroke:#3b82f6,stroke-width:3px,color:#0f172a,rx:12px,ry:12px,font-family:sans-serif;
    linkStyle default stroke:#94a3b8,stroke-width:3px;
  `;
  
  if (styledChart.includes("flowchart LR")) {
    styledChart = styledChart.replace("flowchart LR", "flowchart LR" + boxStyles);
  } else if (styledChart.includes("graph TD")) {
    styledChart = styledChart.replace("graph TD", "graph TD" + boxStyles);
  }

  const encodedChart = btoa(unescape(encodeURIComponent(styledChart)));

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/60 backdrop-blur-sm p-4">
      {/* Reverted exactly back to original modal code */}
      <div className="bg-white dark:bg-[#16181e] w-full max-w-4xl rounded-2xl shadow-2xl p-6 relative overflow-y-auto max-h-[90vh]">
        <button 
          onClick={onClose}
          className="absolute top-4 right-4 w-8 h-8 flex items-center justify-center rounded-full bg-slate-100 hover:bg-slate-200 dark:bg-slate-800 dark:hover:bg-slate-700 text-slate-700 dark:text-slate-300 font-bold"
        >
          ✕
        </button>
        
        <h2 className="text-2xl font-bold mb-6 text-slate-900 dark:text-white">
          Workflow: {projectTitle}
        </h2>
        
        <div className="flex justify-center bg-slate-50 dark:bg-slate-900/50 rounded-xl p-6 border border-slate-200 dark:border-slate-700/50 min-h-[300px]">
          <img 
            src={`https://mermaid.ink/img/${encodedChart}`} 
            alt="Workflow Diagram"
            className="max-w-full h-auto object-contain"
          />
        </div>

        <div className="mt-6 flex justify-end">
          <Button onClick={onClose} variant="secondary">Close Walkthrough</Button>
        </div>
      </div>
    </div>
  );
}
